package com.veterinaria.consentidos.features.person.domain.entity;

import java.time.LocalDateTime;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;

/**
 * Test class for Person entity.
 * Tests validation, constructors, equals/hashCode, and getters/setters.
 */
@DisplayName("Person Entity Tests")
class PersonTest {

    private Validator validator;

    @BeforeEach
    void setUp() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    @Test
    @DisplayName("Should create person with default constructor")
    void testDefaultConstructor() {
        Person person = new Person();
        assertNull(person.getId());
        assertNull(person.getSex());
        assertNull(person.getFirstName());
        assertNull(person.getLastName());
        assertNull(person.getBirthDate());
        assertNull(person.getCity());
        assertNull(person.getDocument());
        assertNull(person.getDocumentType());
    }

    @Test
    @DisplayName("Should create person with parameterized constructor")
    void testParameterizedConstructor() {
        Person person = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        
        assertNull(person.getId()); // ID is generated by JPA
        assertEquals("M", person.getSex());
        assertEquals("Juan", person.getFirstName());
        assertEquals("Perez", person.getLastName());
        assertEquals("Medellin", person.getCity());
        assertEquals("12345678", person.getDocument());
        assertEquals("CC", person.getDocumentType());
    }

    @Test
    @DisplayName("Should validate valid person without violations")
    void testValidPersonValidation() {
        Person person = new Person("F", LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "Gonzalez", "87654321", "TI", "Bogota");
        
        Set<ConstraintViolation<Person>> violations = validator.validate(person);
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("Should reject invalid sex values")
    void testInvalidSexValidation() {
        Person person = new Person("X", LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "Gonzalez", "87654321", "TI", "Bogota");
        
        Set<ConstraintViolation<Person>> violations = validator.validate(person);
        assertEquals(1, violations.size());
        
        ConstraintViolation<Person> violation = violations.iterator().next();
        assertEquals("Sex must be M or F", violation.getMessage());
        assertEquals("sex", violation.getPropertyPath().toString());
    }

    @Test
    @DisplayName("Should reject blank sex")
    void testBlankSexValidation() {
        Person person = new Person("", LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "Gonzalez", "87654321", "TI", "Bogota");
        
        Set<ConstraintViolation<Person>> violations = validator.validate(person);
        assertEquals(2, violations.size()); // NotBlank and Pattern violations
    }

    @Test
    @DisplayName("Should reject null sex")
    void testNullSexValidation() {
        Person person = new Person(null, LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "Gonzalez", "87654321", "TI", "Bogota");
        
        Set<ConstraintViolation<Person>> violations = validator.validate(person);
        assertEquals(1, violations.size());
        
        ConstraintViolation<Person> violation = violations.iterator().next();
        assertEquals("Sex is required", violation.getMessage());
    }

    @Test
    @DisplayName("Should reject blank first name")
    void testBlankFirstNameValidation() {
        Person person = new Person("F", LocalDateTime.of(1985, 6, 20, 0, 0), "", "Gonzalez", "87654321", "TI", "Bogota");
        
        Set<ConstraintViolation<Person>> violations = validator.validate(person);
        assertEquals(1, violations.size());
        
        ConstraintViolation<Person> violation = violations.iterator().next();
        assertEquals("First name is required", violation.getMessage());
    }

    @Test
    @DisplayName("Should reject blank last name")
    void testBlankLastNameValidation() {
        Person person = new Person("F", LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "", "87654321", "TI", "Bogota");
        
        Set<ConstraintViolation<Person>> violations = validator.validate(person);
        assertEquals(1, violations.size());
        
        ConstraintViolation<Person> violation = violations.iterator().next();
        assertEquals("Last name is required", violation.getMessage());
    }

    @Test
    @DisplayName("Should test getters and setters")
    void testGettersAndSetters() {
        Person person = new Person();
        
        person.setId(1L);
        person.setBirthDate(LocalDateTime.of(1990, 1, 15, 0, 0));
        person.setSex("M");
        person.setFirstName("Carlos");
        person.setLastName("Rodriguez");
        person.setCity("Cali");
        person.setDocument("11111111");
        person.setDocumentType("CC");
        
        assertEquals(1L, person.getId());
        assertEquals(LocalDateTime.of(1990, 1, 15, 0, 0), person.getBirthDate());
        assertEquals("M", person.getSex());
        assertEquals("Carlos", person.getFirstName());
        assertEquals("Rodriguez", person.getLastName());
        assertEquals("Cali", person.getCity());
        assertEquals("11111111", person.getDocument());
        assertEquals("CC", person.getDocumentType());
    }

    @Test
    @DisplayName("Should be equal to same object")
    void testEqualsSameObject() {
        Person person = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        assertEquals(person, person);
    }

    @Test
    @DisplayName("Should not be equal to null")
    void testEqualsWithNull() {
        Person person = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        assertNotEquals(person, null);
    }

    @Test
    @DisplayName("Should not be equal to object of different class")
    void testEqualsWithDifferentClass() {
        Person person = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        String otherObject = "Not a Person";
        assertNotEquals(person, otherObject);
    }

    @Test
    @DisplayName("Should be equal when documents are same")
    void testEqualsWithSameDocument() {
        Person person1 = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        Person person2 = new Person("F", LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "Gonzalez", "12345678", "CC", "Bogota");
        
        assertEquals(person1, person2);
    }

    @Test
    @DisplayName("Should not be equal when documents are different")
    void testEqualsWithDifferentDocument() {
        Person person1 = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        Person person2 = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "87654321", "CC", "Medellin");
        
        assertNotEquals(person1, person2);
    }

    @Test
    @DisplayName("Should have consistent hashCode")
    void testHashCodeConsistency() {
        Person person = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        int hashCode1 = person.hashCode();
        int hashCode2 = person.hashCode();
        
        assertEquals(hashCode1, hashCode2);
    }

    @Test
    @DisplayName("Should have same hashCode for same document")
    void testHashCodeWithSameDocument() {
        Person person1 = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        Person person2 = new Person("F", LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "Gonzalez", "12345678", "CC", "Bogota");
        
        assertEquals(person1.hashCode(), person2.hashCode());
    }

    @Test
    @DisplayName("Should not have same hashCode for different documents")
    void testHashCodeWithDifferentDocument() {
        Person person1 = new Person("M", LocalDateTime.of(1990, 1, 15, 0, 0), "Juan", "Perez", "12345678", "CC", "Medellin");
        Person person2 = new Person("F", LocalDateTime.of(1985, 6, 20, 0, 0), "Maria", "Gonzalez", "87654321", "TI", "Bogota");

        assertNotEquals(person1.hashCode(), person2.hashCode());
    }
}