# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:consentidos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway desactivado para perfil local (H2)
spring.flyway.enabled=false

# H2 console (accesible en http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# MVC
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
